name: Build

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheel:
    name: Build wheels
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        # Include all history and tags
        with:
          fetch-depth: 0

      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build wheels
        run: |
          pip install wheel
          pip wheel --no-deps -w dist .

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        # Include all history and tags
        with:
          fetch-depth: 0

      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build sdist
        run: |
          python setup.py sdist

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheel, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write
    environment: secure_publish_environment
    steps:
      - uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
