name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: pip install riot==0.9.0
      - run: riot -v run check_fmt
      - run: riot -v run -s mypy
      - run: riot -v run -s flake8

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install riot
        # Note that pip3 has to be used since the system pip when running
        # under the 2.7 instance will be Python 2 pip.
        # (riot is not Python 2 compatible)
        run: pip3 install riot==0.9.0
      - run: |
          riot run -p ${{ matrix.python-version}} test
